version: '2'
services:
  db:
    image: mariadb
    env_file:
      - ./mariadb.env
  postfix:
    build:
      context: .
      dockerfile: ./Dockerfile.postfix
    image: nocturnal/postfix:latest    
    ports:
      - 25
      - 465
      - 587
    volumes:
      - "../postfix:/etc/postfix"
      - "../dovecot:/etc/dovecot"
    depends_on:
      - unbound
      - db
      - rspamd
      - dovecot
  rspamd:
    build:
      dockerfile: ./Dockerfile.rspamd
      context: .
    image: nocturnal/rspamd:latest
    ports: 
     - 8080
     - 80
     - 9900
     - 11332
    volumes: 
      - "../rspamd:/tmp"
    depends_on:
      - unbound
      - db
  unbound:
    build:
      dockerfile: ./Dockerfile.unbound
      context: .
    image: nocturnal/unbound:latest
    ports: 
     - 53
  dovecot:
    build:
      dockerfile: ./Dockerfile.dovecot
      context: .
    image: nocturnal/dovecot:latest
    ports: 
     - 225
     - 993
     - 143
     - 2525
     - 9000
    volumes: 
      - "../dovecot:/etc/dovecot"
    depends_on:
      - db
