version: '2'
services:
  postfix:
    build:
      context: .
      dockerfile: ./Dockerfile.postfix
    image: nocturnal/postfix:latest    
    ports:
      - "80:80"
    volumes:
      - "../postfix:/etc/postfix"
    depends_on:
      - dovecot
    links:
      - dovecot
    
  dovecot:
    build:
      dockerfile: ./Dockerfile.dovecot
      context: .
    image: nocturnal/dovecot:latest
    ports: 
     - 993
     - 143
    volumes: 
      - "../dovecot:/tmp"

      
