version: '2'
services:
  postfix:
    build:
      context: .
      dockerfile: ./Dockerfile.postfix
    image: nocturnal/postfix:latest    
    ports:
      - 25
      - 465
      - 587
    volumes:
      - "../postfix:/etc/postfix"
      - "../dovecot:/etc/dovecot"
    depends_on:
      - dovecot
    links:
      - dovecot
  dovecot:
    build:
      dockerfile: ./Dockerfile.dovecot
      context: .
    image: nocturnal/dovecot:latest
    ports: 
     - 225
     - 993
     - 143
     - 2525
     - 9000
    volumes: 
      - "../dovecot:/etc/dovecot"

      
