FROM ubuntu:16.04
MAINTAINER Andrew Mason <andrew@nocturnal.net.au>
ENV DEBIAN_FRONTEND noninteractive

COPY rspamd.gpg.key /tmp/
RUN apt-key add /tmp/rspamd.gpg.key

RUN echo "deb http://rspamd.com/apt-stable/ xenial main" > /etc/apt/sources.list.d/rspamd.list & \
 apt-get update && apt-get -y --no-install-recommends install rspamd 

#EXPOSE 9900
#COPY rspamd.conf /etc/rspamd/rspamd.conf
CMD ["/usr/bin/rspamd","-f", "-u", "_rspamd", "-g", "_rspamd"]

