#!/bin/bash
postfix_image="ubuntu:16.04"
postfix_src_config=`readlink -f "../postfix"`
postfix_dest_config="/tmp/postfix"
# You need a network setup in docker for this
postfix_ip='10.8.8.4'

# Am I running?
imageID=`docker ps -f names=$postfix_image|sed -n 2p| awk -e '{print $1}'`

if [[ -z $imageID ]]; then
    echo "Image not running "
    echo "Starting it up for you"
    docker run -it --name postfix --rm --net dev --ip $postfix_ip -v $postfix_src_config:$postfix_dest_config $postfix_image /bin/bash
    wait $!

else 
    echo "image id is $imageID"
    docker stop $imageID
    echo "Waiting for container to stop\n"
    wait $!
    echo "Boom!"
fi

