#!/bin/bash
postfix_image="ubuntu:16.04"
postfix_src_config=`readlink -f "../postfix"`
postfix_dest_config="/tmp/postfix"

# Am I running?
imageID=`docker ps -f names=$postfix_image|sed -n 2p| awk -e '{print $1}'`

if [[ -z $imageID ]]; then
    echo "Image not running "
    echo "Starting it up for you"
    docker run -it --name postfix --rm -v $postfix_src_config:$postfix_dest_config $postfix_image /bin/bash
    wait $!

else 
    echo "image id is $imageID"
    docker stop $imageID
    echo "Waiting for container to stop\n"
    wait $!
    echo "Boom!"
fi

#MWM Containers 
#docker stop 
#docker rm mwm_php
#docker run -d --name mwm_php --net dev  --ip 10.8.8.2 -v /home/am/projects/phalcontest:/srv/www/mwm mwm/php


# NGINX
#docker stop mwm_web
#docker rm mwm_web
#docker run -d --name mwm_web --net dev  --ip 10.8.8.3 -v /home/am/projects/phalcontest:/srv/www/mwm --link mwm_php:mwm_php mwm/nginx
